# Generated by Django 5.1.2 on 2024-11-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='59222b4f1d5d4076a1198c8f0017203b', max_length=255, unique=True),
        ),
    ]
