# Generated by Django 5.1.2 on 2024-11-13 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_admin_referrallink_referral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_chatmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='app.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.admin_category'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.admin_subcategory'),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='4647600fe75943aca68265a264c62a67', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images_ad/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos_ad/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reason',
            field=models.TextField(choices=[('Payment Methods', 'Payment Methods'), ('Refund a Course', 'Refund a Course'), ('Troubleshoot Payment Failure', 'Troubleshoot Payment Failure'), ('Download Course Resources', 'Download Course Resources'), ('Enrollment', 'Enrollment'), ('Grades & Assignments', 'Grades & Assignments'), ('Video Library', 'Video Library'), ('Trust & Safety', 'Trust & Safety'), ('Find a missing course', 'Find a missing course'), ('Other', 'Other')], max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Admin_Ticket',
        ),
    ]
