# Generated by Django 5.1.2 on 2024-11-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_admin_chatmessage_ticket_ticket_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='86cb11a6e51e44a48e48e99e5f9ca76e', max_length=255, unique=True),
        ),
    ]
