# Generated by Django 5.1.2 on 2024-11-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebyprovider',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='app.student'),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='793da8a3bfc347bca155e3f53d75a9e8', max_length=255, unique=True),
        ),
    ]
