# Generated by Django 5.1.2 on 2024-11-23 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_quiz_course_quiz_course_id_quiz_course_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course_type',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='app.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='8a2b48f405484a219389885cefee8650', max_length=255, unique=True),
        ),
    ]
