# Generated by Django 5.1.2 on 2024-11-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_quiz_course_id_remove_quiz_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='ae1bd903c4a445938937fbf028e27cd2', max_length=255, unique=True),
        ),
    ]
