# Generated by Django 5.1.2 on 2024-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_admin_referrallink_referral_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_pic',
            field=models.ImageField(blank=True, upload_to='admin_covers/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_courses',
            field=models.ManyToManyField(to='app.course'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='admin_thumbnails/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='32718d93832043ec8fc17ba899cdaa95', max_length=255, unique=True),
        ),
    ]
