# Generated by Django 5.1.2 on 2024-11-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blogpost_cover_pic_blogpost_related_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='fd0e8f8a1aa4426c8b7432986e77efe6', max_length=255, unique=True),
        ),
    ]
