# Generated by Django 5.1.2 on 2024-11-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_blogpost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='provider',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.admin_courseprovider'),
        ),
        migrations.AddField(
            model_name='course',
            name='skills_you_will_gain',
            field=models.TextField(default='No details provided'),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='00ff1685bb3440dab123baf6a2e42f86', max_length=255, unique=True),
        ),
    ]
