# Generated by Django 5.1.2 on 2024-11-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_course_is_active_course_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='25fa7ef1c4314920999b37f458d770fa', max_length=255, unique=True),
        ),
    ]
