# Generated by Django 5.1.2 on 2024-12-28 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_admin_referrallink_referral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='d5048371f6604d7abb9f39dfa53c1849', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='provider',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.admin_courseprovider'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user__user_type': 2}, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
