# Generated by Django 5.1.1 on 2025-03-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_admin_enrolleduser_enrollment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin_referrallink",
            name="referral_link",
            field=models.CharField(
                default="942429ce1ae447a5995afecadbf71985", max_length=255, unique=True
            ),
        ),
    ]
