# Generated by Django 5.1.1 on 2025-03-28 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_alter_admin_referrallink_referral_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin_referrallink",
            name="referral_link",
            field=models.CharField(
                default="dd65e98dab494ff89100ca65be857ba5", max_length=255, unique=True
            ),
        ),
        migrations.CreateModel(
            name="CourseYouTubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "video_id",
                    models.CharField(
                        help_text="Enter the YouTube Video ID (the part after 'v=')",
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_videos",
                        to="app.course",
                    ),
                ),
            ],
        ),
    ]
