# Generated by Django 5.1.1 on 2025-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_alter_admin_referrallink_referral_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin_referrallink",
            name="referral_link",
            field=models.CharField(
                default="e9bd805aca6046e5bfb857e34cf1f523", max_length=255, unique=True
            ),
        ),
    ]
