# Generated by Django 5.1.1 on 2025-05-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_admin_referrallink_referral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='9e1ea70285cd4d6991ba9017f6c995ca', max_length=255, unique=True),
        ),
    ]
