# Generated by Django 5.1.1 on 2025-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_admin_referrallink_referral_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('expert', 'expert')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_lesson',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='b47895e59e2f447aa173a70b1f07a736', max_length=255, unique=True),
        ),
    ]
