# Generated by Django 5.1.1 on 2025-05-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_course_course_level_course_total_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='4c356b6610254865b744db70237e2756', max_length=255, unique=True),
        ),
    ]
