# Generated by Django 5.1.1 on 2025-05-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_admin_referrallink_referral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='129b99b5419b478ab743992d8ba6bfa2', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='courseyoutubevideo',
            name='video_id',
            field=models.CharField(help_text="Enter the YouTube Video ID (the part after 'v=')", max_length=250),
        ),
        migrations.AlterField(
            model_name='topic',
            name='video_link',
            field=models.CharField(help_text='Copy and past the url of youtube', max_length=250, null=True),
        ),
    ]
