# Generated by Django 5.1.1 on 2025-05-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_admin_referrallink_referral_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='9cc9707135cd433ea2122cfaaac74f6a', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='video_link',
            field=models.CharField(help_text="Enter the YouTube Video ID (the part after 'v=')", max_length=250, null=True),
        ),
    ]
