# Generated by Django 5.1.1 on 2025-05-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_admin_referrallink_referral_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='88a0adf401ce4d2dbd65bfa43d09a836', max_length=255, unique=True),
        ),
    ]
