# Generated by Django 5.1.1 on 2025-05-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_admin_referrallink_referral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='22a65209de684d70a461869469bf2922', max_length=255, unique=True),
        ),
    ]
