# Generated by Django 5.1.1 on 2025-05-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_admin_referrallink_referral_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='54f0913f39d0419586c9cc32f5bce3f4', max_length=255, unique=True),
        ),
    ]
