# Generated by Django 5.1.1 on 2025-05-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_week_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultbyprovider',
            name='created_up',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='486d002ea0cc487aaa262cd242eb979a', max_length=255, unique=True),
        ),
    ]
