# Generated by Django 5.1.1 on 2025-05-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_resultbyprovider_created_up_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultbyprovider',
            old_name='created_up',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='8ff5f72274094688be319fc05f6e66ed', max_length=255, unique=True),
        ),
    ]
