# Generated by Django 5.1.1 on 2025-05-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_created_up_resultbyprovider_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='895ec34809ed48e6a3bff34a643363a8', max_length=255, unique=True),
        ),
    ]
