# Generated by Django 5.1.1 on 2025-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_admin_referrallink_referral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='50010dd936d24f39996c9854f5a0850a', max_length=255, unique=True),
        ),
    ]
