# Generated by Django 5.1.1 on 2025-05-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_admin_referrallink_referral_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerguidancemessage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='career_guidance/'),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='43b5f21484054369be2b4a4cabd3fd9d', max_length=255, unique=True),
        ),
    ]
