# Generated by Django 5.1.1 on 2025-05-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_careerguidancemessage_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerguidancemessage',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='1d6a46bb30fa40e09dab2b91054e4c03', max_length=255, unique=True),
        ),
    ]
