# Generated by Django 5.1.1 on 2025-05-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_rename_thumbnail_careerguidancemessage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='answer',
            field=models.FileField(blank=True, upload_to='question_papers_answer/'),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='03aa7daa76224af1b1e79c0f3b50dec8', max_length=255, unique=True),
        ),
    ]
