# Generated by Django 5.1.1 on 2025-05-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_questionpaper_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='593d75ebaca2466ebce21622281fe8fd', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
