# Generated by Django 5.1.1 on 2025-05-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_admin_referrallink_referral_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='8ad904d1611d4c0bae1848daf8e723b4', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
