# Generated by Django 5.1.1 on 2025-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_admin_referrallink_referral_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video_hash',
            field=models.CharField(help_text="Enter the YouTube Video ID (the part after 'v=')", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='f3af03ad533a4b4eb584f95e29413d88', max_length=255, unique=True),
        ),
    ]
