# Generated by Django 5.1.1 on 2025-05-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_topic_video_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_affiliatemarketer',
            name='name',
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='account_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='account_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='account_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='ifsc_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='image',
            field=models.ImageField(blank=True, upload_to='affiliate_marketer/'),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='password1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='password2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin_affiliatemarketer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='16dbfff470e949a393722e68c38e63e8', max_length=255, unique=True),
        ),
    ]
