# Generated by Django 5.1.1 on 2025-05-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_admin_affiliatemarketer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_affiliatemarketer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='admin_courseprovider',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='47f48e19ccda4ccb96e64808ea1841cf', max_length=255, unique=True),
        ),
    ]
