# Generated by Django 5.1.1 on 2025-05-25 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_rename_first_name_admin_affiliatemarketer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_affiliatemarketer',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='266db0a89e554290b519ce25890c3b99', max_length=255, unique=True),
        ),
    ]
