# Generated by Django 5.1.1 on 2025-05-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_admin_affiliatemarketer_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_affiliatemarketer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='3e501908694a4161a360be09d00269c7', max_length=255, unique=True),
        ),
    ]
