# Generated by Django 5.1.1 on 2025-05-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_admin_affiliatemarketer_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_affiliatemarketer',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='admin_affiliatemarketer',
            name='password2',
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='89cb83489e284b5c8e5487a0df3343c9', max_length=255, unique=True),
        ),
    ]
