# Generated by Django 5.1.1 on 2025-05-27 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_rename_password1_admin_affiliatemarketer_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_payment',
            name='marketer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.admin_affiliatemarketer'),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='d4fd256c73e94cbf9297c3e2311e190d', max_length=255, unique=True),
        ),
    ]
