# Generated by Django 5.1.1 on 2025-05-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_admin_mentor_email_admin_mentor_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_courseprovider',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='7f3e4cbeb82c4b978ba0e0675f10117e', max_length=255, unique=True),
        ),
    ]
