# Generated by Django 5.1.1 on 2025-05-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_admin_courseprovider_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_courseprovider',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='59913f9abe924194a40191d84531ebcd', max_length=255, unique=True),
        ),
    ]
