# Generated by Django 5.1.1 on 2025-05-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_admin_courseprovider_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_courseprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='43402e319cdd46e3912e2eb9a04db7e3', max_length=255, unique=True),
        ),
    ]
