# Generated by Django 5.1.1 on 2025-05-27 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_admin_courseprovider_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_courseprovider',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='ea6d9e273b7b490db6bb7389c7551bfa', max_length=255, unique=True),
        ),
    ]
