# Generated by Django 5.1.1 on 2025-05-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_admin_courseprovider_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='94a34d2e1ce048aca539491ae2555ffd', max_length=255, unique=True),
        ),
    ]
