# Generated by Django 5.1.1 on 2025-06-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_admin_referrallink_referral_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_signature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='220e3435075347e391364865ce8c3f5d', max_length=255, unique=True),
        ),
    ]
