# Generated by Django 5.1.1 on 2025-06-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_paymenthistory_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='ae50347659574f7883d72c8a4785e8af', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='order_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_signature',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
