# Generated by Django 5.1.1 on 2025-06-04 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_admin_referrallink_referral_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='e3f7dc7d61a4417781f504ed3f5a51e6', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='course_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='receipt_invoice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
