# Generated by Django 4.2.23 on 2025-07-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_admin_referrallink_referral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_referrallink',
            name='referral_link',
            field=models.CharField(default='406a830a6ea241ccbc3b2b3307ece83c', max_length=255, unique=True),
        ),
    ]
